### ISSUE TITLE
Доработать страницу "Проведение праздников"

### ISSUE THREAD

**Issue by alex1ozr** [Artyom774/at-seven-lakes#18]
- Под заголовком разместить 2 фотографии панорамного вида – 850х400
- Фотографии горизонтальные (500х375) – 4 шт. видно, далее по стрелкам можно листать. 
- Выравнять ленту с фотографиями 
<img width="485" alt="image" src="https://github.com/Artyom774/at-seven-lakes/assets/39774874/37b26b6a-a6b9-4d1d-951d-c5cdf22b8f4d">

- Текст должен иметь абзацы, не идти сплошной стеной, как на фото ниже
<img width="438" alt="image" src="https://github.com/Artyom774/at-seven-lakes/assets/39774874/69421e74-c969-4bdc-aa39-7bca81300066">

**Comment by Artyom774** [comment]
"Текст должен иметь абзацы, не идти сплошной стеной, как на фото ниже" - и так уже есть на сайте

![image](https://github.com/Artyom774/at-seven-lakes/assets/95544600/47fdc119-ce50-4ed1-97dd-c8448831a3c2)

**Comment by alex1ozr** [comment]
Отлично!
Осталось тогда

- Под заголовком разместить 2 фотографии панорамного вида – 850х400
- Фотографии горизонтальные (500х375) – 4 шт. видно, далее по стрелкам можно листать.
- Выравнять ленту с фотографиями

**Comment by Artyom774** [comment]
Страницу попросить выпилить вообще полностью
